name: mindpebble
favicon: null
layout_spectrum: 0.5047387534286827
typography_spectrum: 0.45543987723067403
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#08070c'
    - '#192845'
    - '#6e4a47'
    - '#81849b'
    - '#ddc585'
  brandStrength: 0
  lightness: 0
  saturation: 0.21236148453317583
  rhythmicContrast: 0.25
purpose: []
