name: mindpebble
favicon: null
layout_spectrum: 0.5047387534286827
typography_spectrum: 0.45543987723067403
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5251275433693081
  lightness: 0.9661731475498527
  saturation: 0.21236148453317583
  rhythmicContrast: 0.05472325743176043
purpose: []
